### ISSUE TITLE
Improve formatting on Wizard Spell Dialog

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#167]
The Mercurial effect box has some overlapping elements.  Even just moving the line below the roll/effect boxes would make it look like it wasn't broken in some way.

Also the "Spell Check" box just looks odd with the 1d20 spaced so far from the +2.  Spell check box is also missing it's outline and should be spaced out away from the "Spell Level" box, which should be much shorter.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/49695/110245120-31bb3c00-7f1f-11eb-97f3-20df71026591.png">

**Comment by mooped** [comment]
Ignoring the rest of the issue for a second, the Spell Check field is missing the outline because it's greyed out when Inherit Spell Check is checked. We can override Foundry's default styling for a disabled field if necessary, but we'd have to do it consistently (non-editable sheets, for example).

**Comment by mooped** [comment]
I'm not a big fan of the way Foundry styles h1/h2 with the underline implemented as a bottom border.

I've made some tweaks to truncate the underline to the length of the element on these sheets, hopefully it makes the intent of the inset summary box clear. If not we can move it under, but I suspect that will also be hard to make look right. We mainly have a separate summary box to allow notes to show on the Equipment tab where possible. We can't use the actual description for this because it's a) too long and b) either leaks HTML formatting into the item sheet or shows the HTML formatting in the edit box.

![image](https://user-images.githubusercontent.com/371357/111922666-e6626b00-8a92-11eb-84c8-391a0026bd86.png)

**Comment by mooped** [comment]
Another option would be to go with the underline thing, though this example looks pretty ugly:

![image](https://user-images.githubusercontent.com/371357/111922788-bebfd280-8a93-11eb-8de4-e0c261671f2a.png)

**Comment by cyface** [comment]
> Ignoring the rest of the issue for a second, the Spell Check field is missing the outline because it's greyed out when Inherit Action Die and/or Inherit Spell Check are checked. We can override Foundry's default styling for a disabled field if necessary, but we'd have to do it consistently (non-editable sheets, for example).

I wonder why Spell Level is not greyed out, or the rest of the fields for that matter? 🤔  Can we at least make the field for the die on the spell check much shorter, so there is a gap between the die and bonus fields? Or even just summarize them as a single value, if they aren't editable (e.g. 1d14+4)?

I don't think the large "Description" header is adding much here - I think it's pretty clear that is the description.  Could we perhaps just add a border line *above* "Mercurial Effect" (and no underline under it), and have the title be vertically centered with the roll/summary stuff?
